version: '3'

services:
  webserver:
    build: 
      context: ./.docker/bin/webserver
    container_name: 'developer_php'
    restart: 'always'
    ports:
      - "8005:80"
      - "4438:443"
    links: 
      - postgres
    volumes: 
      - ${DOCUMENT_ROOT}:/var/www/html
      - ${PHP_INI}:/usr/local/etc/php/php.ini
      - ${VHOSTS_DIR}:/etc/apache2/sites-enabled
      - ${MYSQL_LOG_DIR}:/var/log/apache2

  postgres:
    image: postgres:12.3-alpine
    # build: 
    #  context: ./.docker/bin/postgres/12/alpine
    container_name: 'developer_postgres'
    # privileged: true
    restart: always
    environment:
      POSTGRES_USER: developer
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: developer
    ports:
      - '5432:5432'
    volumes: 
      - ${POSTGRES_SQL_DATA_DIR}:/var/lib/postgresql/data
      - ${POSTGRES_SQL_LOG_DIR}:/var/log/postgresql

  mongo:
    image: mongo
    container_name: 'developer-mongo'
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: developer
    volumes:
      - ${MONGO_DATA_DIR}:/data/db
    ports:
      - '27017:27017'

  mysql:
    build: ./.docker/bin/mysql
    container_name: developer_mysql
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes: 
      - ${MYSQL_DATA_DIR}:/var/lib/mysql
      - ${MYSQL_LOG_DIR}:/var/log/mysql
    ports:
      - ${MYSQL_PORT}:3306

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: 'developer-phpmyadmin'
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - '8089:80'
    volumes: 
      - /sessions

  pgadmin4:
    image: "dpage/pgadmin4"
    # build: 
    #   context: ./bin/pgadmin4
    container_name: 'developer_pgadmin4'
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "15433:80"
    volumes:
      # - ./data/pgadmin4:/var/lib/pgadmin
      - ${PGADMIN4_DATA_DIR}:/var/lib/pgadmin
    depends_on:
      - postgres

  redis:
    image: redis:latest
    container_name: 'developer-redis'
    restart: always
    ports:
      - "63780:6379"
    volumes:
      - ${REDIS_DATA_DIR}:/data
    environment:
      - REDIS_REPLICATION_MODE=master

volumes:
  pgdata:
  pgadmindata:
  mongodata:
  mysqldata:
