language: node_js
node_js:
  - 10
  - 11
  - 12

cache:
  directories:
    - node_modules
    - $HOME/.cache/Cypress

install:
  - yarn install
  - yarn build --modern=client

script:
  - yarn lint
  - yarn start -- --silent &
  - yarn cypress run

addons:
  apt:
    packages:
    - libgconf-2-4
